format_version: 3
pipelines:
  deploy_to_cluster_two:
    group: kubernetes
    environment_variables:
    materials:
      upstream:
        pipeline: deploy_to_uat
        stage: approval_stage
      SourceCodeRepo:
        git: https://github.com/gocd-demo/node-bulletin-board.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - deploy_to_cluster:
        approval:
          type: success
        jobs:
          deploy:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  EnvironmentVariablePrefix: ''
                  SkipImagePulling: 'true'
                artifact_id: bulletin-board
                pipeline: build_and_package
                stage: build_stage
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                arguments:
                command: ./app-deployment.sh
                run_if: passed