format_version: 4
pipelines:
  deploy_to_prod:
    group: kubernetes
    display_order: 3
    environment_variables:
      NAMESPACE: gocd
    secure_variables:
      KUBE_TOKEN: iZ2mMpisGM7k8Cb3ZbsZcw==:vlZsGeONsm8iiUIK4Q3PKCjjlwYJL0hVsduPMpU4JFBoy/RnSK4VuE/RDreZeaBKRLL1YcT1a298inJJ4A1hd5BjIfDYDYaiMqKZxaaOwUbNJiIldntoNZJXxT/Aun4xaBPZYMYNDfBa5zNXPPCtO74D62KENH10ybKaMOEzac2PyesSjYq/ySL9/I+u+J4TNdrE6aRQ9mfPCnAti4Jkwnq0JnjUU9YXMHJqw3CdGeO3Uny0ji5U+MIwiI9cWZECZgW+a5oXBYaDD8c+KdGI/Jrhblb497uHGKn9rLGJMjvfeXBHlVMvmTzvq17FrCk20wHDh8mwoaxNNsMT4YeBM0PqarhA5sAH5D2Ry4kKEGhR3JZ6epAHn/hXRecubNf9aaj2UdGL2yFewRsw0pAb+yAyXf16XgfyEUJce7H9p4Jg5s9LPn6p8KTRvYrPgG9azgvp0FMkM9py/NuvNxuwSx00oVzfAJUuQDBQsBpTsimjX2xo8eZlnW/Y0IlcABvVQbhKyAEX0vdgKtQS2xIzyoVJxGyyFuBsa49VQmAKNAwcScesTOcCkJomRFhJFGNnnQnoMQdNX/2c3K8807Lgu89OVyj8OerRsmIA8WYjQVAwwpbPJwMLusPCqFZCE/Gt5emzwnwntrIhaOt8jCf2qw4F5cPk52y67ekvk1/pzf/19AL1DdbG3GC5AXjGaj0Hg+dAWWQQ7UWRSyxNyDYq2v/sAvLod4BLg+7KeR2iPjGvUtSOKwTxSYnEs2jCM5WBox6Fwn6LshwMW540oMoRj9KQBtQqKhjHJ3/b5fk+u8kh8YSaOl+8Vo5lJW1w0m1hvmWG6kiZ/90AXm1zKiohyu0C0KOFljNmp1C6rrpFO1zNYnlXxp6ZahTa5Yimi3fRZhOImncUV0dlKl0vQI2YT4cxjzIKHh55zE7vXZj2e5l5oGW7YYMAErI+S2r3F2ipTchE8H1t3Z41DgfO6YPi0LkPHy6qsS9A8f2f3RoI7M0SjqodvjAl6FSWln7yMW0278Fifu5lyKXc9qZNe8u7WCnR/C93rNO4ZRR4Zezv6/w4IaWm19D+2ahumUzJl10zXDj82KN6XtRWkSRaKqman7ym/sK2IECewXLp6g68kzXoyFUIX4l+SXyvRPkedzV5adka+2KqItO5a/eJfCODE3XFN8g+oc/U4xROjHLu0Fs=
    materials:
      build:
        pipeline: build_and_package
        stage: test_stage
      SourceCodeRepo:
        git: https://github.com/davidstanke/node-bulletin-board.git
        shallow_clone: false
    stages:
    - deploy_to_prod:
        approval:
          type: success
        jobs:
          deploy:
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  EnvironmentVariablePrefix: ''
                  SkipImagePulling: 'true'
                artifact_id: bulletin-board
                pipeline: build_and_package
                stage: build_stage
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                command: ./app-deployment.sh
                arguments:
                run_if: passed
